name: Deploy to Hetzner

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install
        working-directory: ./server

      - name: Build the project
        run: npm run build
        working-directory: ./server

      - name: Copy files to server
        run: |
          ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no root@${{ secrets.SERVER_IP }} "
            mkdir -p /root/radio/server
          "
          rsync -avz --delete -e "ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no" ./server/ root@${{ secrets.SERVER_IP }}:/root/radio/server

      - name: Deploy with PM2
        run: |
          ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no root@${{ secrets.SERVER_IP }} "
            cd /root/radio/server && \
            export NODE_ENV=production && \
            export DATABASE_URL=${{ secrets.DATABASE_URL }} && \
            export DIRECT_URL=${{ secrets.DIRECT_URL }} && \
            pm2 start npm --name server -- run start --update-env || \
            pm2 restart server --update-env
          "
